language: ruby
rvm: "2.0"
before_install: ./bin/travisci/before_install.sh
script: make test-travisci
notifications:
  email: michael@rabbitmq.com
services:
  - rabbitmq
branches:
  only:
    - master
env:
  - RUBY=ruby
  - SLOWNESS=3
