language: ruby
rvm: "2.0"
before_install: ./bin/travisci/before_install.sh
script: make test-travisci
services:
  - rabbitmq
notifications:
  email: michael@rabbitmq.com
branches:
  only:
    - master
env:
  - RUBY=ruby
  - SLOWNESS=3
